MvcKutuphane/MvcKutuphane/Controllers/BookController.cs
using MvcKutuphane.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace MvcKutuphane.Controllers
{
	public class BookController : Controller
	{
		// GET: Book
		MvcKutuphaneEntities1 db = new MvcKutuphaneEntities1();
		public ActionResult Index(string p)
		{
			var books = from k in db.KITAP select k;
			if (!string.IsNullOrEmpty(p))
			{
				books = books.Where(x => x.AD.Contains(p));
			}

			//var books = db.KITAP.ToList();
			return View(books.ToList());
		}
		[HttpGet]
		public ActionResult AddBooks()
		{
			List<SelectListItem> value1 = (from i in db.KATEGORI.ToList()
										   select new SelectListItem
										   {
											   Text = i.AD,
											   Value = i.ID.ToString()
										   }).ToList();
			ViewBag.dgr1 = value1;

			List<SelectListItem> value2 = (from yz in db.YAZAR.ToList()
										   select new SelectListItem
										   {
											   Text = yz.AD + ' ' + yz.SOYAD,
											   Value = yz.ID.ToString()
										   }).ToList();
			ViewBag.dgr2 = value2;
			return View();
		}
		[HttpPost]
		public ActionResult AddBooks(KITAP p)
		{
			var ktg = db.KATEGORI.Where(k => k.ID == p.KATEGORI1.ID).FirstOrDefault();
			var yzr = db.YAZAR.Where(y => y.ID == p.YAZAR1.ID).FirstOrDefault();
			p.KATEGORI1 = ktg;
			p.YAZAR1 = yzr;
			db.KITAP.Add(p);
			db.SaveChanges();
			return RedirectToAction("Index");

		}
		public ActionResult DeleteBook(int id)
		{
			var ktp = db.KITAP.Find(id);
			db.KITAP.Remove(ktp);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		public ActionResult UpdateBook(int id)
		{
			var ktp = db.KITAP.Find(id);
			List<SelectListItem> value1 = (from i in db.KATEGORI.ToList()
										   select new SelectListItem
										   {
											   Text = i.AD,
											   Value = i.ID.ToString()
										   }).ToList();
			ViewBag.dgr1 = value1;

			List<SelectListItem> value2 = (from yz in db.YAZAR.ToList()
										   select new SelectListItem
										   {
											   Text = yz.AD + ' ' + yz.SOYAD,
											   Value = yz.ID.ToString()
										   }).ToList();
			ViewBag.dgr2 = value2;
			return View("UpdateBook", ktp);
		}
		public ActionResult BookUpdate(KITAP p)
		{
			var kitap = db.KITAP.Find(p.ID);
			kitap.AD = p.AD;
			kitap.BASIMYIL = p.BASIMYIL;
			kitap.SAYFA = p.SAYFA;
			kitap.YAYINEVI = p.YAYINEVI;
			kitap.DURUM = true;
			var ktg = db.KATEGORI.Where(k => k.ID == p.KATEGORI1.ID).FirstOrDefault();
			var yzr = db.YAZAR.Where(y => y.ID == p.YAZAR1.ID).FirstOrDefault();
			kitap.KATEGORI = ktg.ID;
			kitap.YAZAR = yzr.ID;
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

MvcKutuphane/MvcKutuphane/Views/Book/AddBooks.cshtml
@model MvcKutuphane.Models.Entity.KITAP
@{
    ViewBag.Title = "AddBooks";
    Layout = "~/Views/Shared/Layaout.cshtml";
}

<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>
<br />
<div id="strip">Yeni Kitap Ekleme Sayfası</div>
<br />
<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Kitap Adı:</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Kategorisi:</label>
        @Html.DropDownListFor(k => k.KATEGORI1.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazarı:</label>
        @Html.DropDownListFor(k => k.YAZAR1.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım Yılı:</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayın Evi:</label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı:</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-success" id="btn1" style="width:100%">Kitap Ekle</button>
    </div>
    <input type="hidden" name="DURUM" value="True" />
</form>

MvcKutuphane/MvcKutuphane/Views/Book/Index.cshtml
@using MvcKutuphane.Models.Entity
@using PagedList
@using PagedList.Mvc
@model List<KITAP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layaout.cshtml";
}

<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>
<br />
<div id="strip">Kitap Listesi</div>
<br />
@using (Html.BeginForm("Index", "Book", FormMethod.Get))
{
    <div style="margin-bottom:10px;margin-top:15px">
        <b>Aranacak Kitap Adını Yazınız...</b>

        @Html.TextBox("p")
        <br /> <br />
        <input type="submit" value="Ara" style="width:100%" />
    </div>
}

<table class="table table-active">
    <tr style="background-color:rgb(252,178,22)">
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kitap Yazarı</th>
        <th>Kategorisi</th>
        <th>Basım Yılı</th>
        <th>Yayın Evi</th>
        <th>Sayfa</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="background-color: #d4d4d4">
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.YAZAR1.AD  @item.YAZAR1.SOYAD</td>
            <td>@item.KATEGORI1.AD</td>
            <td>@item.BASIMYIL</td>
            <td>@item.YAYINEVI</td>
            <td>@item.SAYFA</td>
            <td>@item.DURUM</td>
            <td>@Html.ActionLink("Sil", "DeleteBook", new { id = item.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor musunuz ?')" })</td>
            <td><a href="/Book/UpdateBook/@item.ID" class="btn btn-warning">Güncelle</a></td>
        </tr>

    }
</table>

<a href="/Book/AddBooks/" class="btn btn-success" style="width:100%">Yeni Kitap Ekle</a>

MvcKutuphane/MvcKutuphane/Views/Book/UpdateBook.cshtml
@model MvcKutuphane.Models.Entity.KITAP
@{
    ViewBag.Title = "UpdateBook";
    Layout = "~/Views/Shared/Layaout.cshtml";
}
<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>

@using (Html.BeginForm("BookUpdate", "Book", FormMethod.Post))
{
    <br />
    <div id="strip">Kitap Güncelleme Sayfası</div>
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>KITAP ID :</label>
        @*@Html.LabelFor(k => k.ID)*@
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        @*@Html.LabelFor(k => k.AD)*@
        <label> KITAP ADI : </label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        <br />
        <label> KITAP  KATEGORSİ : </label>
        @Html.DropDownListFor(k => k.KATEGORI1.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        <label> KITAP YAZARI : </label>
        @Html.DropDownListFor(k => k.YAZAR1.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        <br />
        <label> KITAP BASIM YILI : </label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
        <br />
        <label> KITAP YAYINEVİ : </label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })
        <br />
        <label> KITAP SAYFASI : </label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <button class="btn btn-warning" style="width:100%">Kitap Bilgilerini Güncelle</button>
        <input type="hidden" name="DURUM" value="True" />
    </div>
}