MvcKutuphane/MvcKutuphane/Controllers/WriterController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
	public class WriterController : Controller
	{
		// GET: Writer
		MvcKutuphaneEntities1 db = new MvcKutuphaneEntities1();
		public ActionResult Index()
		{
			var values = db.YAZAR.ToList();
			return View(values);
		}
		[HttpGet]
		public ActionResult AddWritter()
		{
			return View();
		}
		[HttpPost]
		public ActionResult AddWritter(YAZAR y)
		{
			db.YAZAR.Add(y);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		public ActionResult DeleteWritter(int id)
		{
			var yazar = db.YAZAR.Find(id);
			db.YAZAR.Remove(yazar);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		public ActionResult UpdateWriter(int id)
		{
			var yzr = db.YAZAR.Find(id);
			return View("UpdateWriter", yzr);
		}
		public ActionResult WriterUpdate(YAZAR p)
		{
			var yzr = db.YAZAR.Find(p.ID);
			yzr.AD = p.AD;
			yzr.SOYAD = p.SOYAD;
			yzr.DETAY = p.DETAY;
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		public ActionResult MyBook(int id)
		{
			var writer = db.KITAP.Where(x => x.YAZAR == id).ToList();
			var yzrad = db.YAZAR.Where(y => y.ID == id).Select(z => z.AD + " " + z.SOYAD).FirstOrDefault();
			ViewBag.yzr = yzrad;
			return View(writer);
		}
	}
}

MvcKutuphane/MvcKutuphane/Views/Writer/AddWritter.cshtml
@model MvcKutuphane.Models.Entity.YAZAR
@{
    ViewBag.Title = "AddWritter";
    Layout = "~/Views/Shared/Layaout.cshtml";
}
<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>
<br />
<div id="strip">Yeni Yazar Ekleme Sayfası</div>
<br />
<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Yazar Adı:</label>
        @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yazar Soyadı:</label>
        @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yazar Detay:</label>
        @Html.TextAreaFor(x => x.DETAY, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-success" id="btn1" style="width:100%">Yeni Yazar Ekle</button>
    </div>
</form>

MvcKutuphane/MvcKutuphane/Views/Writer/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<YAZAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layaout.cshtml";
}
<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>
<br />
<div id="strip">Yazar Listesi</div>
<br />

<table class="table table-active">
    <tr style="background-color:rgb(252,178,22)">
        <th>ID</th>
        <th>Yazar Adı</th>
        <th>Yazar Soyadı</th>
        <th>Yazar Detayı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Kitapları</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="background-color: #d4d4d4">
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.SOYAD</td>
            <td>@item.DETAY</td>
            <td>@Html.ActionLink("Sil", "DeleteWritter", new { id = item.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor musunuz ?')" })</td>
            <td><a href="/Writer/UpdateWriter/@item.ID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Writer/MyBook/@item.ID" class="btn btn-primary">Kitapları</a></td>
        </tr>

    }
</table>

<a href="/Writer/AddWritter/" class="btn btn-success" style="width:100%">Yeni Yazar Ekle</a>

MvcKutuphane/MvcKutuphane/Views/Writer/MyBook.cshtml
@using MvcKutuphane.Models.Entity
@model List<KITAP>
@{
    ViewBag.Title = "MyBook";
    Layout = "~/Views/Shared/Layaout.cshtml";
}

<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>
<br />
<div id="strip">Yazarın Kitapları</div>
<br />
<h4 style="color:#ff6a00">Kitap Yazarı :  @ViewBag.yzr</h4>
<br />
<table class="table table-active">
    <tr style="background-color:rgb(252,178,22)">
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategori</th>
        <th>Yayınevi</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr style="background-color: #d4d4d4">
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.KATEGORI1.AD</td>
            <td>@item.YAYINEVI</td>
        </tr>

    }
</table>

MvcKutuphane/MvcKutuphane/Views/Writer/UpdateWriter.cshtml
@model MvcKutuphane.Models.Entity.YAZAR
@{
    ViewBag.Title = "UpdateWriter";
    Layout = "~/Views/Shared/Layaout.cshtml";
}

<style>
    #strip {
        width: 100%;
        height: 40px;
        padding: 8px;
        background: #d4d4d4;
        color: black;
        text-align: center;
        font-size: 18px
    }
</style>

@using (Html.BeginForm("WriterUpdate", "Writer", FormMethod.Post))
{
    <br />
    <div id="strip">Yazar Güncelleme Sayfası</div>
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>YAZAR ID :</label>
        @*@Html.LabelFor(k => k.ID)*@
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        @*@Html.LabelFor(k => k.AD)*@
        <label> YAZAR ADI : </label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        <br />
        <label> YAZAR SOYADI : </label>
        @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })
        <br />
        <label> YAZAR DETAYI : </label>
        @Html.TextAreaFor(k => k.DETAY, new { @class = "form-control" })
    </div>
    <br />
    <div>
        <button class="btn btn-warning" style="width:100%">Güncelle</button>
    </div>
}